# Generated by Django 3.0.4 on 2020-03-27 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerifiedCustomer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('mob_no', models.CharField(max_length=10)),
                ('last_active', models.DateTimeField(auto_now=True)),
                ('customer_id', models.IntegerField()),
            ],
        ),
    ]
