# Generated by Django 3.0.4 on 2020-03-25 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_category_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='Name',
            new_name='name',
        ),
    ]
