# Generated by Django 3.0.4 on 2020-03-25 22:32

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='image',
            field=models.ImageField(blank=True, upload_to=home.models.get_upload_path_for_product),
        ),
    ]
