# Generated by Django 3.0.4 on 2020-03-25 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_products_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
