# Generated by Django 3.0.4 on 2020-03-25 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20200326_0403'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
