# Generated by Django 3.0.4 on 2020-03-25 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
