# Generated by Django 3.0.4 on 2020-03-27 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_verifirduploader'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VerifirdUploader',
        ),
    ]
