# Generated by Django 3.0.4 on 2020-03-27 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0004_verifirduploader'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VerifirdUploader',
            new_name='VerifiedUploader',
        ),
    ]
