# Generated by Django 3.0.4 on 2020-03-28 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_verifiedcustomer'),
        ('home', '0011_product_uploaded_by'),
        ('order', '0005_auto_20200328_2234'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unconfirmed_order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('added_tocart_date', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Customer')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.Product')),
            ],
        ),
    ]
