# Generated by Django 3.0.4 on 2020-03-28 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_auto_20200329_0130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unconfirmed_order',
            old_name='location',
            new_name='delivery_location',
        ),
    ]
