# Generated by Django 3.0.4 on 2020-03-28 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_auto_20200329_0132'),
    ]

    operations = [
        migrations.AddField(
            model_name='unconfirmed_order',
            name='order_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
