# Generated by Django 3.0.4 on 2020-03-28 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_unconfirmed_order_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unconfirmed_order',
            name='order_id',
        ),
    ]
