# Generated by Django 3.0.4 on 2020-03-28 23:37

from django.db import migrations, models
import django.db.models.deletion
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_verifiedcustomer'),
        ('order', '0010_remove_unconfirmed_order_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unconfirmed_order',
            name='delivery_city',
        ),
        migrations.RemoveField(
            model_name='unconfirmed_order',
            name='delivery_colony',
        ),
        migrations.RemoveField(
            model_name='unconfirmed_order',
            name='delivery_location',
        ),
        migrations.CreateModel(
            name='Order_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products', models.CharField(max_length=1000)),
                ('delivery_name', models.CharField(max_length=50)),
                ('delivery_city', models.CharField(max_length=50)),
                ('delivery_colony', models.CharField(max_length=100)),
                ('delivery_location', location_field.models.plain.PlainLocationField(max_length=63, null=True)),
                ('order_date', models.DateTimeField(auto_now=True)),
                ('product_id', models.CharField(max_length=30)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Customer')),
            ],
        ),
    ]
