# Generated by Django 3.0.4 on 2020-03-28 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_auto_20200329_0507'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_details',
            name='order_price',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
