# Generated by Django 3.0.4 on 2020-03-28 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_order_details_order_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order_details',
            old_name='product_id',
            new_name='order_id',
        ),
    ]
