# Generated by Django 3.0.4 on 2020-03-28 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_auto_20200329_0512'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_details',
            name='delivery_mob_no',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
