# Generated by Django 3.0.4 on 2020-03-29 01:00

from django.db import migrations, models
import django.db.models.deletion
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_verifiedcustomer'),
        ('order', '0014_order_details_delivery_mob_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Successfull_order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products', models.CharField(max_length=1000)),
                ('delivery_name', models.CharField(max_length=50)),
                ('delivery_city', models.CharField(max_length=50)),
                ('delivery_colony', models.CharField(max_length=100)),
                ('delivery_mob_no', models.CharField(max_length=10, null=True)),
                ('delivery_location', location_field.models.plain.PlainLocationField(max_length=63, null=True)),
                ('order_price', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('order_date', models.DateTimeField(auto_now=True)),
                ('order_id', models.CharField(max_length=30)),
                ('delivered', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Customer')),
            ],
        ),
    ]
