# Generated by Django 3.0.4 on 2020-03-29 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_verifiedcustomer'),
        ('home', '0011_product_uploaded_by'),
        ('order', '0015_successfull_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Successfull_order_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('order_date', models.DateTimeField(auto_now=True)),
                ('delivered', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.Customer')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='home.Product')),
            ],
        ),
    ]
