# Generated by Django 3.0.4 on 2020-03-29 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0016_successfull_order_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='successfull_order_details',
            name='order_id',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
